# 🍽️ Zomato Restaurant Data Analysis
### 📊 Mini Capstone Project
### 👩‍💻 Tools Used:
- Python
- Pandas
- Matplotlib
- Seaborn

## 🎯 Project Objective


The objective of this project is to analyze the Zomato restaurant dataset and extract meaningful insights.


### Key Questions:
- Which cities have the highest number of restaurants?
- How are ratings distributed?
- What is the impact of online delivery on ratings?
- What is the relationship between cost and ratings?

## Dataset Source

This dataset is taken form Kaggle(Zomato Dataset).

Used only for educational purposes.

# Import required libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Loading dataset

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving zomato.csv to zomato.csv

In [ ]:
df=pd.read_csv('zomato.csv',encoding='latin-1')

In [ ]:
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [ ]:
df.shape

(9551, 21)

# Dataset information

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB

In [ ]:
df.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

# Identifying and removing missing values

In [ ]:
df.isnull().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9542 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9542 non-null   int64
 1   Restaurant Name       9542 non-null   object
 2   Country Code          9542 non-null   int64
 3   City                  9542 non-null   object
 4   Address               9542 non-null   object
 5   Locality              9542 non-null   object
 6   Locality Verbose      9542 non-null   object
 7   Longitude             9542 non-null   float64
 8   Latitude              9542 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9542 non-null   int64
 11  Currency              9542 non-null   object
 12  Has Table booking     9542 non-null   object
 13  Has Online delivery   9542 non-null   object
 14  Is delivering now     9542 non-null   object
 15  Switch to order menu  9542 non-null   object
 16  Price range           9542 non-null   int64
 17  Aggregate rating      9542 non-null   float64
 18  Rating color          9542 non-null   object
 19  Rating text           9542 non-null   object
 20  Votes                 9542 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.6+ MB

# Identifying and dropping duplicates

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop_duplicates(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9542 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9542 non-null   int64
 1   Restaurant Name       9542 non-null   object
 2   Country Code          9542 non-null   int64
 3   City                  9542 non-null   object
 4   Address               9542 non-null   object
 5   Locality              9542 non-null   object
 6   Locality Verbose      9542 non-null   object
 7   Longitude             9542 non-null   float64
 8   Latitude              9542 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9542 non-null   int64
 11  Currency              9542 non-null   object
 12  Has Table booking     9542 non-null   object
 13  Has Online delivery   9542 non-null   object
 14  Is delivering now     9542 non-null   object
 15  Switch to order menu  9542 non-null   object
 16  Price range           9542 non-null   int64
 17  Aggregate rating      9542 non-null   float64
 18  Rating color          9542 non-null   object
 19  Rating text           9542 non-null   object
 20  Votes                 9542 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.6+ MB

# EDA

In [ ]:
df.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [ ]:
city_count=df.groupby('City')['Restaurant Name'].count().sort_values(ascending=False)
print(city_count.head(10))

City
New Delhi       5473
Gurgaon         1118
Noida           1080
Faridabad        251
Ghaziabad         25
Bhubaneshwar      21
Guwahati          21
Lucknow           21
Ahmedabad         21
Amritsar          21
Name: Restaurant Name, dtype: int64

In [ ]:
city_rating=df.groupby('City')['Aggregate rating'].mean().sort_values(ascending=False)
print(city_rating)

City
Inner City          4.900000
Quezon City         4.800000
Makati City         4.650000
Pasig City          4.633333
Mandaluyong City    4.625000
                      ...
New Delhi           2.438845
Montville           2.400000
Mc Millan           2.400000
Noida               2.036204
Faridabad           1.866932
Name: Aggregate rating, Length: 140, dtype: float64

In [ ]:
df['Has Online delivery'].value_counts()

Has Online delivery
No     7091
Yes    2451
Name: count, dtype: int64

In [ ]:
deliveryrating=df.groupby('Has Online delivery')['Aggregate rating'].mean()
print(deliveryrating)

Has Online delivery
No     2.463517
Yes    3.248837
Name: Aggregate rating, dtype: float64

In [ ]:
df['Average Cost for two'].value_counts()

Average Cost for two
500     900
300     897
400     857
200     687
600     652
       ...
955       1
390       1
410       1
3210      1
545       1
Name: count, Length: 140, dtype: int64

In [ ]:
costrating=df.groupby('Average Cost for two')['Aggregate rating'].mean()
print(costrating)

Average Cost for two
0         3.833333
7         3.725000
10        4.008000
15        3.575000
20        3.696000
            ...
300000    4.000000
350000    4.300000
450000    4.200000
500000    4.900000
800000    4.350000
Name: Aggregate rating, Length: 140, dtype: float64

# Visualization

In [ ]:
city_rating.head(10).plot(kind='bar')
plt.title('Average Ratings by City')
plt.show()

In [ ]:
city_count.head(10).plot(kind='bar')
plt.title('City vs Restaurant count')
plt.xlabel('City')
plt.ylabel('Number of restaurants')
plt.show()

In [ ]:
deliveryrating.plot(kind='bar')
plt.title('Online Delivery vs Ratings')
plt.xlabel('Online Delivery')
plt.ylabel('Average Rating')
plt.show()

In [ ]:
sns.scatterplot(x='Average Cost for two',y='Aggregate rating',data=df)
plt.title('Average Cost vs Ratings')
plt.xlabel('Average Cost')
plt.ylabel('Ratings')
plt.show()

# Insights

- Most restaurants are concentrated on top cities

- Ratings are mostly between 3.5 to 5

- Online delivery is a key factor for high ratings

- Higher cost restaurants tend to have better ratings

# Conclusion

In this project, we performed Data cleaning, Analysis and Visualization on Kaggle Zomato dataset.

We derived meaningful insights that can help improvw business decisions such as location strategy, pricing and delivery services.